### ISSUE TITLE
Long expyriment modules filename crashes expyriment

### ISSUE THREAD

**Issue by fnielsen** [expyriment/expyriment-android-runtime#6]
Long expyriment modules filename crashes expyriment

```
I/python  ( 5316): Traceback (most recent call last):
I/python  ( 5316):   File "start.pyx", line 55, in start (jni/../jni/application/src//start.c:1352)
I/python  ( 5316):   File "expyriment_app/main.py", line 84, in main
I/python  ( 5316):   File "expyriment_app/expyriment/io/_textmenu.py", line 327, in get
I/python  ( 5316):   File "expyriment_app/expyriment/io/_textmenu.py", line 279, in _redraw
I/python  ( 5316):   File "expyriment_app/expyriment/io/_textmenu.py", line 250, in _append_item
I/python  ( 5316):   File "expyriment_app/expyriment/stimuli/_visual.py", line 655, in plot
I/python  ( 5316):   File "expyriment_app/expyriment/stimuli/_visual.py", line 283, in surface_size
I/python  ( 5316):   File "expyriment_app/expyriment/stimuli/_visual.py", line 321, in _get_surface
I/python  ( 5316):   File "expyriment_app/expyriment/stimuli/_textbox.py", line 320, in _create_surface
I/python  ( 5316):   File "expyriment_app/expyriment/stimuli/_textbox.py", line 363, in render_textrect
I/python  ( 5316): Exception: The word Nielsen2014Smartphone_leftright.py is too long to fit in the rect passed.
```

**Comment by fladd** [comment]
Indeed! @lindemann09: the crash results from your TextMenu class. Can you have a look at this, please?

**Comment by fnielsen** [comment]
I suppose it is around line 80-83 of `expyriment_app/main.py`. Make 320 larger. If elements in `items` are shorten then `menu.get()`should not go directly into `project[]`.

**Comment by lindemann09** [comment]
Dear fnielsen,

thanks very much for your bug report. We have fixed the bug. It was basically an issue in Expyriment and not in the runtime. The new version Experiment 0.7.1 will solve it. If you need however a quick solution under can use the last nightly build of Expyriment, which you can download here https://db.tt/dd6yLUUB  (or for ~~Linux~~ Debian/Ubuntu https://launchpad.net/~lindemann09/+archive/expyriment-nightly) .

*\* WARNING : Nightly builds might be unstable **

Best,
Oliver
